{{$PROMETHEUS_STORAGE_CLASS_PROVISIONER := DefaultParam .PROMETHEUS_STORAGE_CLASS_PROVISIONER "kubernetes.io/azure-disk"}}
{{$PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE := DefaultParam .PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE "StandardSSD_LRS"}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: {{$PROMETHEUS_STORAGE_CLASS_PROVISIONER}}
parameters:
  kind: Managed
  storageaccounttype: {{$PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE}}
  cachingmode: ReadOnly
{{if .RetainPD}}
reclaimPolicy: Delete
{{end}}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
